license_id: cc-by
methodology: Direct Observational Data/Anecdotal Data
caveats: These indicators are not intended to serve as official statistics for individual countries, but rather to provide a standardized regional perspective.
dataset_source: Inter-American Development Bank
package_creator: HDX Data Systems Team
private: False
maintainer: aa13de36-28c5-47a7-8d0b-6d7c754ba8c8
owner_org: hdx
data_update_frequency: 90
